-- Migration 005: Seed 50 cameras across 8 cities
-- Data sourced from src-tauri/src/db/seed.rs

INSERT INTO cameras (
    name, slug, camera_type,
    country, country_code, city,
    location, timezone,
    stream_url, stream_type, codec,
    resolution_w, resolution_h,
    category, description_en,
    recording_codec, retention_tier,
    created_at
) VALUES
    -- ─── Tokyo (7) ───────────────────────────────────────────────────────
    ('渋谷スクランブル交差点', 'shibuya-crossing', 'public',
     'Japan', 'JP', 'Tokyo',
     ST_SetSRID(ST_Point(139.7004, 35.6595), 4326), 'Asia/Tokyo',
     'rtsp://cam.placebo.tv/shibuya-crossing/live', 'rtsp', 'h264',
     1920, 1080,
     'city', 'Shibuya Crossing – the world''s busiest pedestrian intersection',
     'h264', 'tier5', NOW()),

    ('東京タワー', 'tokyo-tower', 'public',
     'Japan', 'JP', 'Tokyo',
     ST_SetSRID(ST_Point(139.7454, 35.6586), 4326), 'Asia/Tokyo',
     'rtsp://cam.placebo.tv/tokyo-tower/live', 'rtsp', 'h264',
     1920, 1080,
     'city', 'Tokyo Tower panoramic view',
     'h264', 'tier5', NOW()),

    ('新宿歌舞伎町', 'shinjuku-kabukicho', 'public',
     'Japan', 'JP', 'Tokyo',
     ST_SetSRID(ST_Point(139.7034, 35.6938), 4326), 'Asia/Tokyo',
     'rtsp://cam.placebo.tv/shinjuku-kabukicho/live', 'rtsp', 'h264',
     1920, 1080,
     'city', 'Shinjuku Kabukicho entertainment district',
     'h264', 'tier5', NOW()),

    ('秋葉原電気街', 'akihabara-electric-town', 'public',
     'Japan', 'JP', 'Tokyo',
     ST_SetSRID(ST_Point(139.7731, 35.6984), 4326), 'Asia/Tokyo',
     'rtsp://cam.placebo.tv/akihabara-electric-town/live', 'rtsp', 'h264',
     1920, 1080,
     'city', 'Akihabara Electric Town main street',
     'h264', 'tier5', NOW()),

    ('浅草寺雷門', 'asakusa-kaminarimon', 'public',
     'Japan', 'JP', 'Tokyo',
     ST_SetSRID(ST_Point(139.7966, 35.7115), 4326), 'Asia/Tokyo',
     'rtsp://cam.placebo.tv/asakusa-kaminarimon/live', 'rtsp', 'h264',
     1920, 1080,
     'city', 'Senso-ji Temple Kaminarimon Gate',
     'h264', 'tier5', NOW()),

    ('お台場レインボーブリッジ', 'odaiba-rainbow-bridge', 'public',
     'Japan', 'JP', 'Tokyo',
     ST_SetSRID(ST_Point(139.7753, 35.6308), 4326), 'Asia/Tokyo',
     'rtsp://cam.placebo.tv/odaiba-rainbow-bridge/live', 'rtsp', 'h264',
     1920, 1080,
     'city', 'Rainbow Bridge viewed from Odaiba',
     'h264', 'tier5', NOW()),

    ('首都高速', 'shuto-expressway', 'public',
     'Japan', 'JP', 'Tokyo',
     ST_SetSRID(ST_Point(139.6503, 35.6762), 4326), 'Asia/Tokyo',
     'rtsp://cam.placebo.tv/shuto-expressway/live', 'rtsp', 'h264',
     1920, 1080,
     'traffic', 'Shuto Expressway traffic camera',
     'h264', 'tier5', NOW()),

    -- ─── Moscow (7) ──────────────────────────────────────────────────────
    ('Красная площадь', 'red-square', 'public',
     'Russia', 'RU', 'Moscow',
     ST_SetSRID(ST_Point(37.6208, 55.7539), 4326), 'Europe/Moscow',
     'rtsp://cam.placebo.tv/red-square/live', 'rtsp', 'h264',
     1920, 1080,
     'city', 'Red Square – heart of Moscow',
     'h264', 'tier5', NOW()),

    ('МКАД Кольцевая', 'mkad-ring-road', 'public',
     'Russia', 'RU', 'Moscow',
     ST_SetSRID(ST_Point(37.8420, 55.7700), 4326), 'Europe/Moscow',
     'rtsp://cam.placebo.tv/mkad-ring-road/live', 'rtsp', 'h264',
     1920, 1080,
     'traffic', 'MKAD ring road traffic',
     'h264', 'tier5', NOW()),

    ('Москва-река набережная', 'moscow-river-embankment', 'public',
     'Russia', 'RU', 'Moscow',
     ST_SetSRID(ST_Point(37.6050, 55.7470), 4326), 'Europe/Moscow',
     'rtsp://cam.placebo.tv/moscow-river-embankment/live', 'rtsp', 'h264',
     1920, 1080,
     'nature', 'Moscow River embankment near Kremlin',
     'h264', 'tier5', NOW()),

    ('Тверская улица', 'tverskaya-street', 'public',
     'Russia', 'RU', 'Moscow',
     ST_SetSRID(ST_Point(37.6060, 55.7650), 4326), 'Europe/Moscow',
     'rtsp://cam.placebo.tv/tverskaya-street/live', 'rtsp', 'h264',
     1920, 1080,
     'city', 'Tverskaya Street – main avenue',
     'h264', 'tier5', NOW()),

    ('Парк Горького', 'gorky-park', 'public',
     'Russia', 'RU', 'Moscow',
     ST_SetSRID(ST_Point(37.6030, 55.7312), 4326), 'Europe/Moscow',
     'rtsp://cam.placebo.tv/gorky-park/live', 'rtsp', 'h264',
     1920, 1080,
     'nature', 'Gorky Park central entrance',
     'h264', 'tier5', NOW()),

    ('Москва-Сити', 'moscow-city', 'public',
     'Russia', 'RU', 'Moscow',
     ST_SetSRID(ST_Point(37.5367, 55.7494), 4326), 'Europe/Moscow',
     'rtsp://cam.placebo.tv/moscow-city/live', 'rtsp', 'h264',
     1920, 1080,
     'city', 'Moscow International Business Center skyline',
     'h264', 'tier5', NOW()),

    ('Воробьёвы горы', 'sparrow-hills', 'public',
     'Russia', 'RU', 'Moscow',
     ST_SetSRID(ST_Point(37.5425, 55.7105), 4326), 'Europe/Moscow',
     'rtsp://cam.placebo.tv/sparrow-hills/live', 'rtsp', 'h264',
     1920, 1080,
     'nature', 'Sparrow Hills panoramic view of Moscow',
     'h264', 'tier5', NOW()),

    -- ─── New York (6) ────────────────────────────────────────────────────
    ('Times Square', 'times-square', 'public',
     'United States', 'US', 'New York',
     ST_SetSRID(ST_Point(-73.9855, 40.7580), 4326), 'America/New_York',
     'rtsp://cam.placebo.tv/times-square/live', 'rtsp', 'h264',
     1920, 1080,
     'city', 'Times Square – the crossroads of the world',
     'h264', 'tier5', NOW()),

    ('Brooklyn Bridge', 'brooklyn-bridge', 'public',
     'United States', 'US', 'New York',
     ST_SetSRID(ST_Point(-73.9969, 40.7061), 4326), 'America/New_York',
     'rtsp://cam.placebo.tv/brooklyn-bridge/live', 'rtsp', 'h264',
     1920, 1080,
     'city', 'Brooklyn Bridge pedestrian walkway',
     'h264', 'tier5', NOW()),

    ('Central Park', 'central-park', 'public',
     'United States', 'US', 'New York',
     ST_SetSRID(ST_Point(-73.9654, 40.7829), 4326), 'America/New_York',
     'rtsp://cam.placebo.tv/central-park/live', 'rtsp', 'h264',
     1920, 1080,
     'nature', 'Central Park Bethesda Fountain area',
     'h264', 'tier5', NOW()),

    ('Empire State Building', 'empire-state-building', 'public',
     'United States', 'US', 'New York',
     ST_SetSRID(ST_Point(-73.9857, 40.7484), 4326), 'America/New_York',
     'rtsp://cam.placebo.tv/empire-state-building/live', 'rtsp', 'h264',
     1920, 1080,
     'city', 'Empire State Building observation deck',
     'h264', 'tier5', NOW()),

    ('5th Avenue Traffic', '5th-avenue-traffic', 'public',
     'United States', 'US', 'New York',
     ST_SetSRID(ST_Point(-73.9840, 40.7549), 4326), 'America/New_York',
     'rtsp://cam.placebo.tv/5th-avenue-traffic/live', 'rtsp', 'h264',
     1920, 1080,
     'traffic', '5th Avenue traffic near Rockefeller Center',
     'h264', 'tier5', NOW()),

    ('Statue of Liberty', 'statue-of-liberty', 'public',
     'United States', 'US', 'New York',
     ST_SetSRID(ST_Point(-74.0445, 40.6892), 4326), 'America/New_York',
     'rtsp://cam.placebo.tv/statue-of-liberty/live', 'rtsp', 'h264',
     1920, 1080,
     'city', 'Statue of Liberty from Liberty Island',
     'h264', 'tier5', NOW()),

    -- ─── Mumbai (6) ──────────────────────────────────────────────────────
    ('Marine Drive', 'marine-drive', 'public',
     'India', 'IN', 'Mumbai',
     ST_SetSRID(ST_Point(72.8234, 18.9438), 4326), 'Asia/Kolkata',
     'rtsp://cam.placebo.tv/marine-drive/live', 'rtsp', 'h264',
     1920, 1080,
     'city', 'Marine Drive – Queen''s Necklace',
     'h264', 'tier5', NOW()),

    ('Gateway of India', 'gateway-of-india', 'public',
     'India', 'IN', 'Mumbai',
     ST_SetSRID(ST_Point(72.8347, 18.9220), 4326), 'Asia/Kolkata',
     'rtsp://cam.placebo.tv/gateway-of-india/live', 'rtsp', 'h264',
     1920, 1080,
     'city', 'Gateway of India monument',
     'h264', 'tier5', NOW()),

    ('Bandra-Worli Sea Link', 'bandra-worli-sealink', 'public',
     'India', 'IN', 'Mumbai',
     ST_SetSRID(ST_Point(72.8162, 19.0380), 4326), 'Asia/Kolkata',
     'rtsp://cam.placebo.tv/bandra-worli-sealink/live', 'rtsp', 'h264',
     1920, 1080,
     'traffic', 'Bandra-Worli Sea Link bridge traffic',
     'h264', 'tier5', NOW()),

    ('Juhu Beach', 'juhu-beach', 'public',
     'India', 'IN', 'Mumbai',
     ST_SetSRID(ST_Point(72.8267, 19.0988), 4326), 'Asia/Kolkata',
     'rtsp://cam.placebo.tv/juhu-beach/live', 'rtsp', 'h264',
     1920, 1080,
     'nature', 'Juhu Beach sunset view',
     'h264', 'tier5', NOW()),

    ('CST Station', 'cst-station', 'public',
     'India', 'IN', 'Mumbai',
     ST_SetSRID(ST_Point(72.8355, 18.9398), 4326), 'Asia/Kolkata',
     'rtsp://cam.placebo.tv/cst-station/live', 'rtsp', 'h264',
     1920, 1080,
     'city', 'Chhatrapati Shivaji Terminus – UNESCO heritage',
     'h264', 'tier5', NOW()),

    ('Haji Ali Dargah', 'haji-ali-dargah', 'public',
     'India', 'IN', 'Mumbai',
     ST_SetSRID(ST_Point(72.8089, 18.9827), 4326), 'Asia/Kolkata',
     'rtsp://cam.placebo.tv/haji-ali-dargah/live', 'rtsp', 'h264',
     1920, 1080,
     'city', 'Haji Ali Dargah mosque on islet',
     'h264', 'tier5', NOW()),

    -- ─── Helsinki (6) ────────────────────────────────────────────────────
    ('Сенатская площадь', 'senate-square', 'public',
     'Finland', 'FI', 'Helsinki',
     ST_SetSRID(ST_Point(24.9527, 60.1695), 4326), 'Europe/Helsinki',
     'rtsp://cam.placebo.tv/senate-square/live', 'rtsp', 'h264',
     1920, 1080,
     'city', 'Senate Square with Helsinki Cathedral',
     'h264', 'tier5', NOW()),

    ('South Harbor', 'south-harbor', 'public',
     'Finland', 'FI', 'Helsinki',
     ST_SetSRID(ST_Point(24.9560, 60.1670), 4326), 'Europe/Helsinki',
     'rtsp://cam.placebo.tv/south-harbor/live', 'rtsp', 'h264',
     1920, 1080,
     'harbor', 'South Harbor market square and ferries',
     'h264', 'tier5', NOW()),

    ('Esplanadi Park', 'esplanadi-park', 'public',
     'Finland', 'FI', 'Helsinki',
     ST_SetSRID(ST_Point(24.9451, 60.1674), 4326), 'Europe/Helsinki',
     'rtsp://cam.placebo.tv/esplanadi-park/live', 'rtsp', 'h264',
     1920, 1080,
     'nature', 'Esplanadi Park promenade',
     'h264', 'tier5', NOW()),

    ('Suomenlinna', 'suomenlinna', 'public',
     'Finland', 'FI', 'Helsinki',
     ST_SetSRID(ST_Point(24.9881, 60.1454), 4326), 'Europe/Helsinki',
     'rtsp://cam.placebo.tv/suomenlinna/live', 'rtsp', 'h264',
     1920, 1080,
     'nature', 'Suomenlinna sea fortress – UNESCO site',
     'h264', 'tier5', NOW()),

    ('Mannerheimintie', 'mannerheimintie', 'public',
     'Finland', 'FI', 'Helsinki',
     ST_SetSRID(ST_Point(24.9414, 60.1718), 4326), 'Europe/Helsinki',
     'rtsp://cam.placebo.tv/mannerheimintie/live', 'rtsp', 'h264',
     1920, 1080,
     'traffic', 'Mannerheimintie main avenue traffic',
     'h264', 'tier5', NOW()),

    ('Temppeliaukio Church', 'temppeliaukio-church', 'public',
     'Finland', 'FI', 'Helsinki',
     ST_SetSRID(ST_Point(24.9252, 60.1729), 4326), 'Europe/Helsinki',
     'rtsp://cam.placebo.tv/temppeliaukio-church/live', 'rtsp', 'h264',
     1920, 1080,
     'city', 'Rock Church exterior view',
     'h264', 'tier5', NOW()),

    -- ─── London (6) ──────────────────────────────────────────────────────
    ('Tower Bridge', 'tower-bridge', 'public',
     'United Kingdom', 'GB', 'London',
     ST_SetSRID(ST_Point(-0.0754, 51.5055), 4326), 'Europe/London',
     'rtsp://cam.placebo.tv/tower-bridge/live', 'rtsp', 'h264',
     1920, 1080,
     'city', 'Tower Bridge over the Thames',
     'h264', 'tier5', NOW()),

    ('Trafalgar Square', 'trafalgar-square', 'public',
     'United Kingdom', 'GB', 'London',
     ST_SetSRID(ST_Point(-0.1281, 51.5080), 4326), 'Europe/London',
     'rtsp://cam.placebo.tv/trafalgar-square/live', 'rtsp', 'h264',
     1920, 1080,
     'city', 'Trafalgar Square with Nelson''s Column',
     'h264', 'tier5', NOW()),

    ('Westminster Bridge', 'westminster-bridge', 'public',
     'United Kingdom', 'GB', 'London',
     ST_SetSRID(ST_Point(-0.1218, 51.5007), 4326), 'Europe/London',
     'rtsp://cam.placebo.tv/westminster-bridge/live', 'rtsp', 'h264',
     1920, 1080,
     'city', 'Westminster Bridge and Big Ben view',
     'h264', 'tier5', NOW()),

    ('Piccadilly Circus', 'piccadilly-circus', 'public',
     'United Kingdom', 'GB', 'London',
     ST_SetSRID(ST_Point(-0.1340, 51.5101), 4326), 'Europe/London',
     'rtsp://cam.placebo.tv/piccadilly-circus/live', 'rtsp', 'h264',
     1920, 1080,
     'city', 'Piccadilly Circus neon lights',
     'h264', 'tier5', NOW()),

    ('Thames River', 'thames-river', 'public',
     'United Kingdom', 'GB', 'London',
     ST_SetSRID(ST_Point(-0.0985, 51.5074), 4326), 'Europe/London',
     'rtsp://cam.placebo.tv/thames-river/live', 'rtsp', 'h264',
     1920, 1080,
     'nature', 'Thames River south bank',
     'h264', 'tier5', NOW()),

    ('Oxford Street', 'oxford-street', 'public',
     'United Kingdom', 'GB', 'London',
     ST_SetSRID(ST_Point(-0.1418, 51.5152), 4326), 'Europe/London',
     'rtsp://cam.placebo.tv/oxford-street/live', 'rtsp', 'h264',
     1920, 1080,
     'traffic', 'Oxford Street shopping traffic',
     'h264', 'tier5', NOW()),

    -- ─── Paris (6) ───────────────────────────────────────────────────────
    ('Tour Eiffel', 'eiffel-tower', 'public',
     'France', 'FR', 'Paris',
     ST_SetSRID(ST_Point(2.2945, 48.8584), 4326), 'Europe/Paris',
     'rtsp://cam.placebo.tv/eiffel-tower/live', 'rtsp', 'h264',
     1920, 1080,
     'city', 'Eiffel Tower from Trocadéro',
     'h264', 'tier5', NOW()),

    ('Champs-Élysées', 'champs-elysees', 'public',
     'France', 'FR', 'Paris',
     ST_SetSRID(ST_Point(2.3076, 48.8698), 4326), 'Europe/Paris',
     'rtsp://cam.placebo.tv/champs-elysees/live', 'rtsp', 'h264',
     1920, 1080,
     'city', 'Champs-Élysées avenue towards Arc de Triomphe',
     'h264', 'tier5', NOW()),

    ('Notre-Dame', 'notre-dame', 'public',
     'France', 'FR', 'Paris',
     ST_SetSRID(ST_Point(2.3499, 48.8530), 4326), 'Europe/Paris',
     'rtsp://cam.placebo.tv/notre-dame/live', 'rtsp', 'h264',
     1920, 1080,
     'city', 'Notre-Dame Cathedral reconstruction',
     'h264', 'tier5', NOW()),

    ('Seine River', 'seine-river', 'public',
     'France', 'FR', 'Paris',
     ST_SetSRID(ST_Point(2.3522, 48.8566), 4326), 'Europe/Paris',
     'rtsp://cam.placebo.tv/seine-river/live', 'rtsp', 'h264',
     1920, 1080,
     'nature', 'Seine River near Île de la Cité',
     'h264', 'tier5', NOW()),

    ('Montmartre', 'montmartre', 'public',
     'France', 'FR', 'Paris',
     ST_SetSRID(ST_Point(2.3431, 48.8867), 4326), 'Europe/Paris',
     'rtsp://cam.placebo.tv/montmartre/live', 'rtsp', 'h264',
     1920, 1080,
     'city', 'Montmartre Sacré-Cœur view',
     'h264', 'tier5', NOW()),

    ('Place de la Concorde', 'place-de-la-concorde', 'public',
     'France', 'FR', 'Paris',
     ST_SetSRID(ST_Point(2.3212, 48.8656), 4326), 'Europe/Paris',
     'rtsp://cam.placebo.tv/place-de-la-concorde/live', 'rtsp', 'h264',
     1920, 1080,
     'traffic', 'Place de la Concorde roundabout',
     'h264', 'tier5', NOW()),

    -- ─── Dubai (6) ───────────────────────────────────────────────────────
    ('Burj Khalifa', 'burj-khalifa', 'public',
     'United Arab Emirates', 'AE', 'Dubai',
     ST_SetSRID(ST_Point(55.2744, 25.1972), 4326), 'Asia/Dubai',
     'rtsp://cam.placebo.tv/burj-khalifa/live', 'rtsp', 'h264',
     1920, 1080,
     'city', 'Burj Khalifa – tallest building in the world',
     'h264', 'tier5', NOW()),

    ('Dubai Marina', 'dubai-marina', 'public',
     'United Arab Emirates', 'AE', 'Dubai',
     ST_SetSRID(ST_Point(55.1403, 25.0805), 4326), 'Asia/Dubai',
     'rtsp://cam.placebo.tv/dubai-marina/live', 'rtsp', 'h264',
     1920, 1080,
     'city', 'Dubai Marina skyline and yachts',
     'h264', 'tier5', NOW()),

    ('Palm Jumeirah', 'palm-jumeirah', 'public',
     'United Arab Emirates', 'AE', 'Dubai',
     ST_SetSRID(ST_Point(55.1390, 25.1124), 4326), 'Asia/Dubai',
     'rtsp://cam.placebo.tv/palm-jumeirah/live', 'rtsp', 'h264',
     1920, 1080,
     'city', 'Palm Jumeirah aerial view',
     'h264', 'tier5', NOW()),

    ('Dubai Creek', 'dubai-creek', 'public',
     'United Arab Emirates', 'AE', 'Dubai',
     ST_SetSRID(ST_Point(55.2975, 25.2644), 4326), 'Asia/Dubai',
     'rtsp://cam.placebo.tv/dubai-creek/live', 'rtsp', 'h264',
     1920, 1080,
     'nature', 'Dubai Creek traditional dhow boats',
     'h264', 'tier5', NOW()),

    ('Sheikh Zayed Road', 'sheikh-zayed-road', 'public',
     'United Arab Emirates', 'AE', 'Dubai',
     ST_SetSRID(ST_Point(55.2708, 25.2048), 4326), 'Asia/Dubai',
     'rtsp://cam.placebo.tv/sheikh-zayed-road/live', 'rtsp', 'h264',
     1920, 1080,
     'traffic', 'Sheikh Zayed Road traffic – main highway',
     'h264', 'tier5', NOW()),

    ('Jumeirah Beach', 'jumeirah-beach', 'public',
     'United Arab Emirates', 'AE', 'Dubai',
     ST_SetSRID(ST_Point(55.2340, 25.2048), 4326), 'Asia/Dubai',
     'rtsp://cam.placebo.tv/jumeirah-beach/live', 'rtsp', 'h264',
     1920, 1080,
     'nature', 'Jumeirah Beach with Burj Al Arab backdrop',
     'h264', 'tier5', NOW());
