-- 010_seed_alpha_cameras.sql
-- Alpha-release camera roster: 13 YouTube live + 5 looped-MP4 demos.
-- Replaces the deleted 005 seed entirely – this is the only camera seed.

-- LIVE YouTube cameras (13)
INSERT INTO cameras (
    name, slug, camera_type,
    country, country_code, city,
    location, timezone,
    stream_url, stream_type,
    stream_source_type, stream_source_config,
    category, description_en,
    resolution_w, resolution_h, codec,
    height_above_ground, camera_azimuth, camera_elevation, fov_horizontal, fov_vertical,
    added_to_placebo_at, created_at
) VALUES
    ('Shibuya Crossing – Live',     'yt-shibuya-crossing', 'public',
     'Japan', 'JP', 'Tokyo',
     ST_SetSRID(ST_Point(139.7004, 35.6595), 4326), 'Asia/Tokyo',
     'youtube://dfVK7ld38Ys', 'youtube',
     'youtube_live', '{"videoId":"dfVK7ld38Ys"}'::jsonb,
     'city', 'Shibuya Crossing live',
     1920, 1080, 'h264',
     8, 180, -20, 80, 50,
     NOW(), NOW()),

    ('Times Square – NYC Live',     'yt-times-square', 'public',
     'United States', 'US', 'New York',
     ST_SetSRID(ST_Point(-73.9857, 40.7580), 4326), 'America/New_York',
     'youtube://u4UZ4UvZXrg', 'youtube',
     'youtube_live', '{"videoId":"u4UZ4UvZXrg"}'::jsonb,
     'city', 'Times Square live panoramic',
     1920, 1080, 'h264',
     12, 90, -10, 90, 55,
     NOW(), NOW()),

    ('Abbey Road Crossing – London','yt-abbey-road', 'public',
     'United Kingdom', 'GB', 'London',
     ST_SetSRID(ST_Point(-0.1779, 51.5320), 4326), 'Europe/London',
     'youtube://FQWkgr0aHlI', 'youtube',
     'youtube_live', '{"videoId":"FQWkgr0aHlI"}'::jsonb,
     'city', 'Abbey Road zebra crossing live',
     1920, 1080, 'h264',
     4, 0, -30, 70, 45,
     NOW(), NOW()),

    ('Helsinki Senate Square',      'yt-helsinki-senate', 'public',
     'Finland', 'FI', 'Helsinki',
     ST_SetSRID(ST_Point(24.9525, 60.1699), 4326), 'Europe/Helsinki',
     'youtube://AdUw5RdyZxI', 'youtube',
     'youtube_live', '{"videoId":"AdUw5RdyZxI"}'::jsonb,
     'city', 'Senate Square & Helsinki Cathedral',
     1920, 1080, 'h264',
     20, 135, -12, 85, 50,
     NOW(), NOW()),

    ('Red Square – Moscow',         'yt-red-square', 'public',
     'Russia', 'RU', 'Moscow',
     ST_SetSRID(ST_Point(37.6208, 55.7539), 4326), 'Europe/Moscow',
     'youtube://h1wly909BYw', 'youtube',
     'youtube_live', '{"videoId":"h1wly909BYw"}'::jsonb,
     'city', 'Red Square live feed',
     1920, 1080, 'h264',
     10, 180, -8, 90, 52,
     NOW(), NOW()),

    ('Gateway of India – Mumbai',   'yt-gateway-mumbai', 'public',
     'India', 'IN', 'Mumbai',
     ST_SetSRID(ST_Point(72.8347, 18.9220), 4326), 'Asia/Kolkata',
     'youtube://7Bl5p4VTXzQ', 'youtube',
     'youtube_live', '{"videoId":"7Bl5p4VTXzQ"}'::jsonb,
     'city', 'Gateway of India',
     1920, 1080, 'h264',
     6, 90, -15, 80, 50,
     NOW(), NOW()),

    ('Dubai Marina',                'yt-dubai-marina', 'public',
     'United Arab Emirates', 'AE', 'Dubai',
     ST_SetSRID(ST_Point(55.1403, 25.0777), 4326), 'Asia/Dubai',
     'youtube://2L4yhCmGRWg', 'youtube',
     'youtube_live', '{"videoId":"2L4yhCmGRWg"}'::jsonb,
     'city', 'Dubai Marina skyline',
     1920, 1080, 'h264',
     40, 45, -20, 85, 50,
     NOW(), NOW()),

    ('Eiffel Tower cam',            'yt-eiffel', 'public',
     'France', 'FR', 'Paris',
     ST_SetSRID(ST_Point(2.2945, 48.8584), 4326), 'Europe/Paris',
     'youtube://dyWHmEQAVUI', 'youtube',
     'youtube_live', '{"videoId":"dyWHmEQAVUI"}'::jsonb,
     'city', 'Eiffel Tower live',
     1920, 1080, 'h264',
     25, 300, -5, 85, 50,
     NOW(), NOW()),

    ('Venice – Rialto Bridge',      'yt-rialto-venice', 'public',
     'Italy', 'IT', 'Venice',
     ST_SetSRID(ST_Point(12.3359, 45.4380), 4326), 'Europe/Rome',
     'youtube://qMksIqJv3pI', 'youtube',
     'youtube_live', '{"videoId":"qMksIqJv3pI"}'::jsonb,
     'city', 'Grand Canal at Rialto',
     1920, 1080, 'h264',
     5, 180, -10, 80, 50,
     NOW(), NOW()),

    ('Seoul – Gwanghwamun Square',  'yt-gwanghwamun', 'public',
     'South Korea', 'KR', 'Seoul',
     ST_SetSRID(ST_Point(126.9768, 37.5759), 4326), 'Asia/Seoul',
     'youtube://wNmMr_ATI2E', 'youtube',
     'youtube_live', '{"videoId":"wNmMr_ATI2E"}'::jsonb,
     'city', 'Gwanghwamun Square',
     1920, 1080, 'h264',
     8, 0, -12, 85, 50,
     NOW(), NOW()),

    ('Barcelona – La Rambla',       'yt-la-rambla', 'public',
     'Spain', 'ES', 'Barcelona',
     ST_SetSRID(ST_Point(2.1724, 41.3809), 4326), 'Europe/Madrid',
     'youtube://hSbkw-F7bzY', 'youtube',
     'youtube_live', '{"videoId":"hSbkw-F7bzY"}'::jsonb,
     'city', 'La Rambla pedestrian street',
     1920, 1080, 'h264',
     6, 90, -15, 80, 50,
     NOW(), NOW()),

    ('Bondi Beach – Sydney',        'yt-bondi', 'public',
     'Australia', 'AU', 'Sydney',
     ST_SetSRID(ST_Point(151.2767, -33.8908), 4326), 'Australia/Sydney',
     'youtube://2Te5EvOXNZw', 'youtube',
     'youtube_live', '{"videoId":"2Te5EvOXNZw"}'::jsonb,
     'beach', 'Bondi Beach live',
     1920, 1080, 'h264',
     10, 60, -8, 90, 55,
     NOW(), NOW()),

    ('Amsterdam Canals',            'yt-amsterdam-canal', 'public',
     'Netherlands', 'NL', 'Amsterdam',
     ST_SetSRID(ST_Point(4.8917, 52.3730), 4326), 'Europe/Amsterdam',
     'youtube://SkdGPWUUkEw', 'youtube',
     'youtube_live', '{"videoId":"SkdGPWUUkEw"}'::jsonb,
     'city', 'Amsterdam canal loop',
     1920, 1080, 'h264',
     4, 180, -10, 80, 50,
     NOW(), NOW());

-- DEMO loop_mp4 cameras (5)
-- Assets are uploaded by the developer to crates/placebo-api/static/demo/<asset>/
-- (HLS-segmented MP4 + index.m3u8 generated by FFmpeg). The proxy 302-redirects
-- to /static/demo/<asset>/index.m3u8.
INSERT INTO cameras (
    name, slug, camera_type,
    country, country_code, city,
    location, timezone,
    stream_url, stream_type,
    stream_source_type, stream_source_config,
    category, description_en,
    resolution_w, resolution_h, codec,
    height_above_ground, camera_azimuth, camera_elevation, fov_horizontal, fov_vertical,
    added_to_placebo_at, created_at
) VALUES
    ('Demo – Tokyo Alley',     'demo-tokyo-alley', 'public',
     'Japan', 'JP', 'Tokyo',
     ST_SetSRID(ST_Point(139.7014, 35.6598), 4326), 'Asia/Tokyo',
     'loop://tokyo-alley', 'hls',
     'loop_mp4', '{"asset":"tokyo-alley","durationS":92}'::jsonb,
     'city', 'Looped demo – Tokyo alley',
     1280, 720, 'h264',
     6, 120, -15, 80, 50,
     NOW(), NOW()),

    ('Demo – Cafe Street',     'demo-cafe-street', 'public',
     'France', 'FR', 'Paris',
     ST_SetSRID(ST_Point(2.3500, 48.8566), 4326), 'Europe/Paris',
     'loop://cafe-street', 'hls',
     'loop_mp4', '{"asset":"cafe-street","durationS":120}'::jsonb,
     'city', 'Looped demo – Parisian cafe street',
     1280, 720, 'h264',
     4, 240, -8, 80, 50,
     NOW(), NOW()),

    ('Demo – Beach Sunset',    'demo-beach-sunset', 'public',
     'Spain', 'ES', 'Valencia',
     ST_SetSRID(ST_Point(-0.3700, 39.4700), 4326), 'Europe/Madrid',
     'loop://beach-sunset', 'hls',
     'loop_mp4', '{"asset":"beach-sunset","durationS":180}'::jsonb,
     'beach', 'Looped demo – sunset at the beach',
     1280, 720, 'h264',
     8, 270, -5, 90, 55,
     NOW(), NOW()),

    ('Demo – Rainy Window',    'demo-rainy-window', 'public',
     'Russia', 'RU', 'Saint Petersburg',
     ST_SetSRID(ST_Point(30.3351, 59.9343), 4326), 'Europe/Moscow',
     'loop://rainy-window', 'hls',
     'loop_mp4', '{"asset":"rainy-window","durationS":240}'::jsonb,
     'weather', 'Looped demo – rainy window',
     1280, 720, 'h264',
     3, 0, -20, 60, 40,
     NOW(), NOW()),

    ('Demo – Mountain Pass',   'demo-mountain-pass', 'public',
     'Switzerland', 'CH', 'Zermatt',
     ST_SetSRID(ST_Point(7.7491, 46.0207), 4326), 'Europe/Zurich',
     'loop://mountain-pass', 'hls',
     'loop_mp4', '{"asset":"mountain-pass","durationS":150}'::jsonb,
     'mountain', 'Looped demo – alpine pass',
     1280, 720, 'h264',
     12, 45, -10, 85, 50,
     NOW(), NOW());
